name: nginx-proxy-manager
services:
  app:
    image: 'chishin/nginx-proxy-manager-zh:release'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - npm-data:/data
      - npm-crypt:/etc/letsencrypt
volumes:
  npm-data:
  npm-crypt:
